### ISSUE TITLE
When available

### ISSUE THREAD

**Issue by gustavz** [jetsonhacks/buildLibrealsense2TX#1]
Hey Jetsonhacks,

very nice that you take ont this challange!
Do you already know when this repo will be finished?

I am just starting with the D435 on the Jetson, is there already a way to get them both working together?

Cheers
Gustav

**Comment by eleboss** [comment]
+1
I am also so glad to see this repo.
I am following the link below, trying to install librealsense2.10 in TX2. 
https://github.com/IntelRealSense/librealsense/blob/development/doc/installation_jetson.md
and meet a lot problems.

Wating for a good answer.
Cheers
Jeremy

**Comment by jetsonhacks** [comment]
Version 0.5 has been released.

**Comment by jetsonhacks** [comment]
Version 0.5 has been released.
