### ISSUE TITLE
Seg fault with the examples

### ISSUE THREAD

**Issue by kmonte** [jetsonhacks/buildLibrealsense2TX#14]
I ran the scripts with 
` ./buildPatchedKernel.sh`

`sudo reboot 0`

`./installLibrealsense.sh`

And when I try to run the example code (either rs-capture or realsense-viewer) on my tx2 I segfault and coredump.

**Comment by kmonte** [comment]
It turns out the examples were segfaulting when I was running over ssh (with X forwarding enabled).

**Comment by jetsonhacks** [comment]
Do they run on board the Jetson?

**Comment by kmonte** [comment]
Yes they do run on board the Jetson.

Do you have any potential solutions/reasons as to why they don't work with X forwarding?

**Comment by jetsonhacks** [comment]
This is a question better asked on the librealsense Github account. This repository simply holds scripts to install librealsense2 on a Jetson TX Development Kit. If the library appears to work correctly onboard the Jetson, anything past that is beyond what this repository can help with.

**Comment by kmonte** [comment]
Ok, thanks.

Additionally (again I'm not sure if this is out of scope for you), the realsense examples do not seem to be using the gpu.

**Comment by jetsonhacks** [comment]
As far as GPU usage, that has not my experience. See this article: https://www.jetsonhacks.com/2018/07/10/librealsense-update-nvidia-jetson-tx-dev-kits/
If you go about 8:20 into the video, there is a graph of GPU usage.

**Comment by dan9thsense** [comment]
Same problem here with ssh -X connection causes segfault.  If you find a solution, please post back here.
