### ISSUE TITLE
A workable way and some threads for people who need.

### ISSUE THREAD

**Issue by eleboss** [jetsonhacks/buildLibrealsense2TX#2]
Basically the same time, I successfully install the librealsense2 in a TX2 with J120 carrier board In jetpack3.2.

My procedure as follow:
```
Flash the TX2 by using jetpack 3.2(with J120 USB patch, if you are using official board, just ignore)
Using jetpack3.0 to install CUDA8.0 and cudnn5.1
git clone https://github.com/freemanlo/librealsense
cd librealsense/scripts/
gedit patch-utils.sh
delete line 138
`sudo rm ${tgt_ko}.bckup`
save
sudo apt-get install libusb-1.0-0-dev pkg-config cmake git libglfw3-dev qtcreator cmake-curses-gui build-essential libgtk-3-dev libssd-dev
cd  ../
./scripts/patch-realsense-ubuntu-xenial-jetson-tx2.sh 
sudo cp config/99-realsense-libusb.rules /etc/udev/rules.d/
sudo udevadm control --reload-rules && udevadm trigger
install opencv by using https://github.com/jetsonhacks/buildOpenCVTX2 (ignore if you have already done that)
mkdir build && cd build
cmake ../ -DBUILD_EXAMPLES=true
make && sudo make install

``` 
 
some thread may help:

Install in Jetpack 3.2 (Intel provided an official patch script)
https://github.com/IntelRealSense/librealsense/issues/1424

Install in Jetpack3.1
https://github.com/IntelRealSense/librealsense/issues/1095  (I simply tested and some file can't be downloaded)

Best

**Comment by gustavz** [comment]
why are you not cloning librealsense from the original repo?

**Comment by eleboss** [comment]
this repo is the same as the official repo except a patch script for tx2 provided by the RealSense Customer Engineering team, you can see that at IntelRealSense/librealsense#1424

**Comment by jetsonhacks** [comment]
These instructions are a partial solution, refer to the repository for further development.
