### ISSUE TITLE
no display

### ISSUE THREAD

**Issue by k-lam** [jetsonhacks/buildLibrealsense2TX#5]
I hava built the realsense follow your sugestion, and install successfully
my steps:
1. flash os,install cuda
2. run script:getKernelSourcesNoGUI.sh from https://github.com/jetsonhacks/buildJetsonTX2Kernel
3. run ./installLibrealsense.sh
4. run sudo ./scripts/patchKernel.sh
5. run sudo ./scripts/configureKernel.sh

**Comment by jetsonhacks** [comment]
I do not understand what "no display" means. It appears that you configured the kernel, but did not make or install it. What version of L4T are you running?

**Comment by k-lam** [comment]
@jetsonhacks means monitor shows no signal.
And when and how should I make or instal the kernel?run makeKernel.sh before installing Librealsense
version:L4T 28.2.0 [ JetPack 3.2 ]

**Comment by jetsonhacks** [comment]
Are you using a Jetson TX1 or a TX2?
If you are using a TX1, it is possible that you ran out of disk space.
If you did not make the kernel or install it, then there have been no changes to your core system, and it should work properly. You can examine the serial console to see why the machine is not booting correctly.

You can examine the script "buildPatchedKernel.sh" for the commands and sequence that are typically used to build the kernel and install it. It is assumed that you are an intermediate level developer and familiar with building the kernel onboard the Jetson TX. There are articles, videos and GitHub repositories for building the kernel:

Jetson TX1: https://www.jetsonhacks.com/2018/04/21/build-kernel-and-modules-nvidia-jetson-tx1/
Jetson TX2: https://www.jetsonhacks.com/2018/03/22/build-kernel-modules-nvidia-jetson-tx2-2/

If you are not comfortable building your own kernel, then you can flash the Jetson and then run the buildPatchedKernel script which will do all of the heavy lifting for you.

**Comment by jetsonhacks** [comment]
There hasn't been any response to this, closing.
