### ISSUE TITLE
pull request to for small bug fix

### ISSUE THREAD

**Issue by Changliu52** [jetsonhacks/buildLibrealsense2TX#9]
Please checkout this quick pull request for pkg-config 
[https://github.com/jetsonhacks/buildLibrealsense2TX/pull/8](url)

**Comment by jetsonhacks** [comment]
I like this fix, however I incorporated it differently. The jetson_variables script is from a different author/repository and I want to keep it consistent with their work. The fix for this script was to move the error out on a script error past the jetson_variables script call. 5d66f6a

**Comment by jetsonhacks** [comment]
Bug fix added: 5d66f6a
